### ISSUE TITLE
Does not work with Podman :(

### ISSUE THREAD

**Issue by rahilarious** [KSmanis/docker-gentoo-distcc#35]
Probably not your images' fault, cause happens same with my custom image. Works on docker but not on podman. Same command, same image. 

You know any fix? Tried on fedora 37

**Comment by henning-schild** [comment]
Not true. I just (4h ago) created a fed39 node to help my gentoo machines gain some speed.

It is not the first time i am doing that and am pretty sure i used f37 as well at some point.

```
dnf install podman
podman pull docker.io/ksmanis/gentoo-distcc:tcp
podman run -d -p 3632:3632 --name gentoo-distcc-tcp --rm ksmanis/gentoo-distcc:tcp
```

Maybe you can provide more details on what failed and how it did. Or you recheck on i.e. f39.

I suggest to close this one at some point.

**Comment by KSmanis** [comment]
Thanks for the feedback @henning-schild. I might look into podman smoke tests in the CI, but IIRC podman was a bit of a hassle to set up in GitHub Actions.

**Comment by henning-schild** [comment]
> Thanks for the feedback @henning-schild. I might look into podman smoke tests in the CI, but IIRC podman was a bit of a hassle to set up in GitHub Actions.

This container is simple enough so that it will likely  just work. Probably not worth the effort, maybe wait for the next such issue, or the first "real" one.
