### ISSUE TITLE
Gentoo stable is on GCC 12 

### ISSUE THREAD

**Issue by mbartosi** [KSmanis/docker-gentoo-distcc#36]
But latest docker image as of 06.02.2023 is still on GCC 11.3:

cd /usr/x86_64-pc-linux-gnu/gcc-bin/
9d1134fe7aba /usr/x86_64-pc-linux-gnu/gcc-bin # ls
11.3.0

Could you move to GCC 12?

**Comment by KSmanis** [comment]
Fixed as of `20230305`:
```shell
$ docker run --rm ksmanis/gentoo-distcc:ssh-20230305 gcc --version
gcc (Gentoo 12.2.1_p20230121-r1 p10) 12.2.1 20230121
```

Thanks for the report.
