### ISSUE TITLE
add ccache support

### ISSUE THREAD

**Issue by henning-schild** [KSmanis/docker-gentoo-distcc#64]
https://wiki.gentoo.org/wiki/Ccache

Lists several reasons why one might want to use dev-util/ccache to potentially speed up builds. For me personally the most prominent would be that i have multiple machines running gentoo. But i do not build my own binary packages, which would be an alternative approach to "share work". Sharing with distcc and ccache seems promising for sure and i have been using ccache for a while now on my gentoo nodes.

However i now also have a relatively powerful fedora node in my network and like to offload compilation to it, here i use the container from this repo. The idea is that my less powerful machines, like my laptop, do not actually compile too much on their own and let the server do most of the work. Having ccache on that server would allow sharing already compiled results across clients.

A ccache can even be shared by many nodes i.e. with nfs or samba. But that is not related to the container.

First of all i would like to know if a ccache feature for this container image would be of interest. If so i could prepare a PR and we could discuss further.

It would boil down to installing a package in the container, configure some things and bind-mount the folder with the cache. Maybe some hooks to initialize the cache, conditions on when or when not to use it etc. And some way to get stats out of the container should the container host not have ccache installed to inspect the shared folder.

Let me know what you think.

**Comment by KSmanis** [comment]
I'm not opposed to such a feature in principle, but my final say would depend on the maintenance burden. If the configuration is straightforward, CI is robust, and there are smoke tests, I would consider it for inclusion. If not, I guess you can maintain it in your fork or a downstream image.

Thanks!

**Comment by Goosegit11** [comment]
https://github.com/KSmanis/docker-gentoo-distcc/pull/66#issuecomment-2367775883

**Comment by Goosegit11** [comment]
Thanks for the explanation! :-)
