### ISSUE TITLE
`HEALTHCHECK CMD` distorts `ccache` stats

### ISSUE THREAD

**Issue by henning-schild** [KSmanis/docker-gentoo-distcc#69]
The healthcheck seems to launch a compiler which will cause false cache hits on the healtcheck interval.

What happens:

```
docker run -d ksmanis/gentoo-distcc:tcp-ccache
docker exec <hash> ccache -sv
```

The distcc service from the container has never been used, the port is not even exposed. But we see something causing constant cache hits over time

```
...
Cacheable calls:     22 /  22 (100.0%)
  Hits:              21 /  22 (95.45%)
    Direct:           0 /  21 ( 0.00%)
    Preprocessed:    21 /  21 (100.0%)
  Misses:             1 /  22 ( 4.55%)
...
```

For a real ccache a long idling container will give the false impression that the "real" hit rate is higher than it actually is. The healcheck cmd should leave the cache stats untouched.

**Comment by henning-schild** [comment]
One minor thing, maybe a side-effect of having the cache enabled by default and also setting the PATH for the healtcheck. I did not investigate yet, for now just reporting

**Comment by KSmanis** [comment]
You are right; I was aware that the `HEALTHCHECK` has access to ccache, but did not consider that it would distort the stats. I will fix it.

**Comment by henning-schild** [comment]
Thanks for looking into it!

**Comment by henning-schild** [comment]
I think tcp did not run that healtcheck before, but am not sure and did not switch back to an older container. When i checked `podman ps` i saw something about healtcheck which i think i did not see in the past. But i could be wrong or maybe updated podman over time.

**Comment by KSmanis** [comment]
The updated `HEALTHCHECK` just performs a port scan and will therefore not trigger ccache. However, you may find it a bit noisier than before. In that case feel free to [turn it off](https://github.com/KSmanis/docker-gentoo-distcc/discussions/41#discussioncomment-6464404) or redefine it to something more to your liking.
