### ISSUE TITLE
 ERROR: mkdir '/dev/null/.distcc' failed: Not a directory

### ISSUE THREAD

**Issue by perdakovich** [KSmanis/docker-gentoo-distcc#71]
I entered the docker container to find the issue why client can't distribute to the host. What I saw is this, and maybe it is the culprit? I'm not sure, I'm just desperate

**Comment by Goosegit11** [comment]
![image](https://github.com/user-attachments/assets/15c2b738-0c2b-46da-8af9-b29c817dd8de)

**Comment by Goosegit11** [comment]
![image](https://github.com/user-attachments/assets/b6aefcdf-c25e-4cd0-bdda-4f09fc492841)

**Comment by Goosegit11** [comment]
![image](https://github.com/user-attachments/assets/0e241417-ec54-40e4-bd7b-9046be5c132d)

**Comment by KSmanis** [comment]
The default user for the `tcp` image is `distcc`, which has no home directory. Try using `docker exec -itu root gentoo-distcc-tcp bash`, to debug the container as root instead, or you'll be limited to the privileges of the `distcc` user.

**Comment by Goosegit11** [comment]
How do you distribute compilers? I have Arch Linux client which has GCC 14.2, and your Gentoo docker container has GCC 13.3
How do I sync them, what are your solutions?

**Comment by KSmanis** [comment]
Only the stable Gentoo tool-chain is currently supported out of the box, you'd have to build your own image if you are interested in different versions, by emerging the appropriate ebuilds.

**Comment by Goosegit11** [comment]
![image](https://github.com/user-attachments/assets/dcddb16d-a889-4e7f-9789-87206a3b6417)

How do I change GCC?
